import type { MenuCategory } from "../menu";

export const dayMenuCategories: MenuCategory[] = [
  {
    name: "Vode",
    items: [
      { name: "Knjaz Miloš 0.25L", price: "120 RSD" },
      { name: "Aqua Viva 0.25L", price: "120 RSD" },
      { name: "Romerquelle 0.33L", price: "250 RSD" },
      { name: "Knjaz Miloš limun 0.33L", price: "220 RSD" },
      { name: "Aqua Viva 0.75L", price: "250 RSD" },
      { name: "Aqua Viva 0.33L", price: "200 RSD" },
      { name: "Knjaz Miloš 0.33L", price: "200 RSD" },
      { name: "Knjaz Miloš limun", price: "140 RSD" },
      { name: "Knjaz Miloš 0.75L", price: "250 RSD" },
      { name: "Romerquelle Carb Mers 0.33", price: "66 RSD" },
      { name: "Knjaz Miloš narandža 0.33L", price: "220 RSD" },
      { name: "Aqua 1L", price: "330 RSD" },
      { name: "Knjaz 1L", price: "330 RSD" },
      { name: "Knjaz mandarina 0.33L", price: "220 RSD" },
    ],
  },
  {
    name: "Energy",
    items: [
      { name: "Guarana 0.25L", price: "290 RSD" },
      { name: "Red Bull 0.25L", price: "400 RSD" },
      { name: "Cedevita", price: "220 RSD" },
      { name: "Ultra Energy", price: "270 RSD" },
    ],
  },
  {
    name: "Kafe",
    items: [
      { name: "Espresso dupli", price: "250 RSD" },
      { name: "Caffe latte", price: "270 RSD" },
      { name: "Domaća kafa", price: "140 RSD" },
      { name: "Espresso", price: "160 RSD" },
      { name: "Espresso mleko", price: "180 RSD" },
      { name: "Espresso šlag", price: "190 RSD" },
      { name: "Capucino Italiani", price: "190 RSD" },
      { name: "Nes kafa", price: "240 RSD" },
      { name: "Domaća kafa mleko", price: "170 RSD" },
      { name: "Kafa sa ukusom", price: "330 RSD" },
      { name: "Ice Caffe", price: "270 RSD" },
      { name: "Affogato", price: "290 RSD" },
      { name: "Staff kafa", price: "40 RSD" },
      { name: "Staff domaća kafa", price: "20 RSD" },
      { name: "Sirup Shot 0.03L", price: "100 RSD" },
      { name: "Irish coffee", price: "450 RSD" },
      { name: "Mocha Caffe", price: "280 RSD" },
      { name: "Espresso + Knjaz Miloš narandža 0.33L", price: "200 RSD" },
      { name: "Americano", price: "180 RSD" },
    ],
  },
  {
    name: "Topli napici",
    items: [
      { name: "Nesquik", price: "200 RSD" },
      { name: "Čaj", price: "160 RSD" },
      { name: "Mleko 0.2L", price: "100 RSD" },
      { name: "Topla čokolada", price: "300 RSD" },
      { name: "Topla čokolada sa šlagom", price: "350 RSD" },
      { name: "Dodatak mleko", price: "30 RSD" },
      { name: "Dodatak med", price: "30 RSD" },
      { name: "Ceđeni limun", price: "100 RSD" },
      { name: "Dodatak šlag", price: "50 RSD" },
      { name: "Dolcezza čaj", price: "150 RSD" },
      { name: "Čaj Dolcezza", price: "150 RSD" },
      { name: "Med", price: "50 RSD" },
      { name: "Sojino mleko 0.165L", price: "80 RSD" },
      { name: "Dodatak plazma", price: "80 RSD" },
      { name: "Sojino mleko 0.1", price: "80 RSD" },
    ],
  },
  {
    name: "Hladni napici",
    items: [
      { name: "Plazma šejk", price: "450 RSD" },
      { name: "Frape", price: "300 RSD" },
      { name: "Sladoled kugla", price: "150 RSD" },
      { name: "Voćni kolač", price: "200 RSD" },
      { name: "Žito", price: "170 RSD" },
      { name: "Čokoladni kolač", price: "200 RSD" },
      { name: "Cheesecake", price: "250 RSD" },
      { name: "Voćni kup", price: "510 RSD" },
      { name: "Banana Split", price: "530 RSD" },
      { name: "Belvil kup", price: "560 RSD" },
    ],
  },
  {
    name: "Gazirani",
    items: [
      { name: "Coca Cola Zero 0.25L", price: "190 RSD" },
      { name: "Fanta 0.25L", price: "190 RSD" },
      { name: "Tonic Water 0.25L", price: "250 RSD" },
      { name: "Coca Cola 0.25L", price: "190 RSD" },
      { name: "Bitter Lemon 0.25L", price: "230 RSD" },
      { name: "Sprite 0.25L", price: "190 RSD" },
      { name: "Kokta 0.25L", price: "290 RSD" },
      { name: "Orangina 0.25L", price: "380 RSD" },
      { name: "Orangina Rouge 0.25L", price: "380 RSD" },
      { name: "Tangerine 0.25L", price: "250 RSD" },
      { name: "Cockta Blondie 0.275L", price: "190 RSD" },
      { name: "Pepsi 0.25L", price: "260 RSD" },
      { name: "Pepsi Max 0.25L", price: "260 RSD" },
      { name: "Mirinda 0.25L", price: "270 RSD" },
      { name: "Evervess 0.25L", price: "290 RSD" },
      { name: "Seven Up 0.25L", price: "270 RSD" },
      { name: "Coca Cola 2L", price: "550 RSD" },
      { name: "Tonic Evervess", price: "290 RSD" },
      { name: "IVI Breskva 0.33L", price: "290 RSD" },
      { name: "Pepsi Twist 0.25L", price: "260 RSD" },
    ],
  },
  {
    name: "Piva",
    items: [
      { name: "Točeno Stella Artois 0.5L", price: "290 RSD" },
      { name: "Točeno Stella Artois 0.25L", price: "220 RSD" },
      { name: "Jelen pivo 0.33L", price: "160 RSD" },
      { name: "Corona 0.355L", price: "360 RSD" },
      { name: "Bavaria 0.25L", price: "190 RSD" },
      { name: "Nikšićko tamno 0.33L", price: "190 RSD" },
      { name: "Staropramen 0.33L", price: "190 RSD" },
      { name: "Točeno Tuborg 0.33L", price: "280 RSD" },
      { name: "Točeno Tuborg 0.5L", price: "340 RSD" },
      { name: "Stella 0.33", price: "250 RSD" },
      { name: "Lav premijum 0.33", price: "300 RSD" },
      { name: "Carlsberg 0.33", price: "230 RSD" },
      { name: "Tuborg 0.33", price: "310 RSD" },
      { name: "Budweiser 0.33", price: "350 RSD" },
      { name: "Kronenbourg 0.33", price: "350 RSD" },
      { name: "San Miguel 0.33", price: "450 RSD" },
      { name: "Erdinger 0.33", price: "470 RSD" },
      { name: "Točeni Tuborg 0.33", price: "130 RSD" },
      { name: "Točeni Tuborg 0.5", price: "170 RSD" },
      { name: "Dodatak kikiriki", price: "150 RSD" },
      { name: "Budweiser dark 0.33", price: "190 RSD" },
      { name: "Bezalkoholno pivo", price: "200 RSD" },
      { name: "Bavarija bezalkoholno 0.25", price: "250 RSD" },
      { name: "Čips", price: "70 RSD" },
      { name: "Carlsberg točeno 0.5", price: "250 RSD" },
      { name: "Carlsberg točeno 0.3", price: "170 RSD" },
      { name: "Carlsberg točeno 0.5L", price: "300 RSD" },
      { name: "Carlsberg točeno 0.33L", price: "250 RSD" },
      { name: "Heineken 0.25L", price: "250 RSD" },
      { name: "Carlsberg 0.25L", price: "330 RSD" },
      { name: "Tuborg Ice 0.33L", price: "310 RSD" },
      { name: "Kronenbourg točeno 0.33", price: "310 RSD" },
      { name: "Kronenbourg točeno 0.5", price: "450 RSD" },
      { name: "Grimbergen Blonde 0.33", price: "300 RSD" },
      { name: "Tuborg Zero 0.33L", price: "320 RSD" },
      { name: "Blanc Malina 0.33L", price: "360 RSD" },
    ],
  },
  {
    name: "Rakije",
    items: [
      { name: "Viljamovka 0.03L", price: "160 RSD" },
      { name: "Šljiva 0.03L", price: "160 RSD" },
      { name: "Loza 0.03L", price: "130 RSD" },
      { name: "Dunja 0.03L", price: "160 RSD" },
      { name: "Kajsija 0.03L", price: "160 RSD" },
      { name: "Meduška Boginja meda 0.03L", price: "250 RSD" },
      { name: "Ouzo", price: "170 RSD" },
      { name: "Zlatna dunja 0.03L", price: "250 RSD" },
      { name: "Zlatna šljiva 0.03L", price: "320 RSD" },
      { name: "Borovnica žuža", price: "200 RSD" },
      { name: "Medica žuža", price: "200 RSD" },
      { name: "Kajsija žuža", price: "200 RSD" },
      { name: "Dunja žuža", price: "250 RSD" },
      { name: "Šljiva žuža", price: "200 RSD" },
      { name: "Dunja art 0.03L", price: "250 RSD" },
      { name: "Šljiva Voćar Kopaonik 0.03L", price: "220 RSD" },
      { name: "Dunja Voćar Kopaonik 0.03L", price: "240 RSD" },
      { name: "Kajsija Voćar Kopaonik 0.03L", price: "240 RSD" },
      { name: "Viljamovka Voćar 0.70L", price: "5000 RSD" },
      { name: "Samar šljiva 0.03L", price: "330 RSD" },
      { name: "Medovina Sokolova 0.03L", price: "330 RSD" },
      { name: "Žarić Koketa višnja 0.03L", price: "270 RSD" },
      { name: "Zlatni tok šljiva 0.03L", price: "390 RSD" },
      { name: "Žarić dunja 0.03L", price: "300 RSD" },
      { name: "Loza 13. Juli", price: "190 RSD" },
      { name: "Šljiva tok", price: "390 RSD" },
      { name: "Viljamovka Takovo 0.03L", price: "270 RSD" },
      { name: "Loza Voćar Kopaonik 0.03L", price: "230 RSD" },
      { name: "Viljamovka Voćar 0.03L", price: "240 RSD" },
      { name: "Borovnica žuža 0.03L", price: "250 RSD" },
      { name: "Šljiva Trivunova 0.03L", price: "220 RSD" },
      { name: "Dunja T 0.03L", price: "190 RSD" },
      { name: "Tequila AG 0.03L", price: "270 RSD" },
      { name: "Dunja Takovo 0.03L", price: "250 RSD" },
    ],
  },
  {
    name: "Kokteli",
    items: [
      { name: "Blue Curacao Koktel", price: "600 RSD" },
      { name: "Aperol Spritz", price: "650 RSD" },
      { name: "Margarita", price: "470 RSD" },
      { name: "Sex on the Beach", price: "650 RSD" },
      { name: "Cosmopolitan", price: "550 RSD" },
      { name: "Long Island", price: "750 RSD" },
      { name: "Tropical", price: "590 RSD" },
      { name: "Strawberry Passion", price: "270 RSD" },
      { name: "Negroni", price: "580 RSD" },
      { name: "Campari Tonic", price: "580 RSD" },
      { name: "Mojito", price: "490 RSD" },
      { name: "Batman", price: "450 RSD" },
      { name: "Piña Colada", price: "480 RSD" },
      { name: "Mojito u boji", price: "450 RSD" },
      { name: "Lime Cooler", price: "550 RSD" },
      { name: "Lime Cooler K", price: "380 RSD" },
      { name: "Sweet Dreams", price: "520 RSD" },
      { name: "Studio Koktel", price: "600 RSD" },
      { name: "Mai Tai", price: "730 RSD" },
      { name: "Gorki List Spritz", price: "530 RSD" },
      { name: "Hugo", price: "530 RSD" },
      { name: "Blue Frog", price: "990 RSD" },
      { name: "God Father", price: "530 RSD" },
      { name: "Monkey", price: "350 RSD" },
      { name: "Tequila Sunrise", price: "890 RSD" },
      { name: "Džin Tonik", price: "350 RSD" },
      { name: "Bitter Vodka", price: "350 RSD" },
      { name: "Bitter Vodka V", price: "350 RSD" },
      { name: "Đus Vodka", price: "350 RSD" },
    ],
  },
];
