import type { MenuCategory } from "../menu";

export const nightMenuCategories: MenuCategory[] = [
  {
    name: "Energy",
    items: [
      { name: "Guarana 0.25L", price: "390 RSD" },
      { name: "Red Bull 0.25L", price: "550 RSD" },
      { name: "Cedevita", price: "330 RSD" },
      { name: "Ultra Energy", price: "350 RSD" },
    ],
  },
  {
    name: "Kafe",
    items: [
      { name: "Espresso dupli", price: "280 RSD" },
      { name: "Caffe latte", price: "350 RSD" },
      { name: "Domaća kafa", price: "180 RSD" },
      { name: "Espresso", price: "200 RSD" },
      { name: "Espresso mleko", price: "220 RSD" },
      { name: "Espresso slag", price: "250 RSD" },
      { name: "Capucino Italiani", price: "250 RSD" },
      { name: "Nes kafa", price: "380 RSD" },
      { name: "Domaća kafa mleko", price: "200 RSD" },
      { name: "Kafa sa ukusom", price: "450 RSD" },
      { name: "Ice Caffe", price: "300 RSD" },
      { name: "Sirup Shot 0.03L", price: "150 RSD" },
      { name: "Irish coffee", price: "650 RSD" },
      { name: "Mocha Caffe", price: "260 RSD" },
      { name: "Americano", price: "250 RSD" },
    ],
  },
  {
    name: "Topli napici",
    items: [
      { name: "Nesquik", price: "250 RSD" },
      { name: "Čaj", price: "280 RSD" },
      { name: "Mleko 0.2L", price: "100 RSD" },
      { name: "Topla čokolada", price: "450 RSD" },
      { name: "Topla čokolada sa šlagom", price: "500 RSD" },
      { name: "Ceđeni limun", price: "200 RSD" },
      { name: "Sojino mleko 0.1", price: "80 RSD" },
    ],
  },
  {
    name: "Hladni napici",
    items: [
      { name: "Plazma šejk", price: "650 RSD" },
      { name: "Frape", price: "450 RSD" },
    ],
  },
  {
    name: "Gazirani",
    items: [
      { name: "Tonic Water 0.25L", price: "300 RSD" },
      { name: "Kokta 0.25L", price: "360 RSD" },
      { name: "Orangina 0.25L", price: "450 RSD" },
      { name: "Orangina Rouge 0.25L", price: "450 RSD" },
      { name: "Tangerine 0.25L", price: "320 RSD" },
      { name: "Pepsi 0.25L", price: "350 RSD" },
      { name: "Pepsi Max 0.25L", price: "350 RSD" },
      { name: "Mirinda 0.25L", price: "350 RSD" },
      { name: "Evervess 0.25L", price: "390 RSD" },
      { name: "Seven Up 0.25L", price: "350 RSD" },
      { name: "Tonic Evervess", price: "390 RSD" },
      { name: "IVI Breskva 0.33L", price: "290 RSD" },
      { name: "Pepsi Twist 0.25L", price: "290 RSD" },
    ],
  },
  {
    name: "Piva",
    items: [
      { name: "Točeno Tuborg 0.33L", price: "400 RSD" },
      { name: "Točeno Tuborg 0.5L", price: "500 RSD" },
      { name: "Lav premijum 0.33", price: "400 RSD" },
      { name: "Tuborg 0.33", price: "450 RSD" },
      { name: "Budweiser 0.33", price: "490 RSD" },
      { name: "Kronenbourg 0.33", price: "490 RSD" },
      { name: "San Miguel 0.33", price: "550 RSD" },
      { name: "Erdinger 0.33", price: "550 RSD" },
      { name: "Dodatak kikiriki", price: "350 RSD" },
      { name: "Carlsberg 0.25L", price: "490 RSD" },
      { name: "Tuborg Ice 0.33L", price: "350 RSD" },
      { name: "Kronenbourg točeno 0.33", price: "450 RSD" },
      { name: "Kronenbourg točeno 0.5", price: "550 RSD" },
      { name: "Grimbergen Blonde 0.33", price: "390 RSD" },
      { name: "Tuborg Zero 0.33L", price: "450 RSD" },
      { name: "Blanc Malina 0.33L", price: "490 RSD" },
    ],
  },
  {
    name: "Vina & cideri",
    items: [
      { name: "Somersby jabuka 0.33L", price: "490 RSD" },
      { name: "Somersby kruška 0.33L", price: "490 RSD" },
      { name: "Somersby borovnica 0.33L", price: "490 RSD" },
      { name: "Somersby mango 0.33", price: "490 RSD" },
      { name: "Somersby jagoda 0.33L", price: "490 RSD" },
      { name: "Aleksić Barbara 0.187L", price: "750 RSD" },
      { name: "Aleksić žuti cvet 0.187L", price: "900 RSD" },
      { name: "Klub Krstac 0.187L", price: "650 RSD" },
      { name: "Klub Rose 0.187L", price: "650 RSD" },
      { name: "Klub Vranac 0.187L", price: "650 RSD" },
      { name: "Aleksandrija belo vino 0.187L", price: "850 RSD" },
      { name: "Chardonnay Kovačević 0.75L", price: "3800 RSD" },
      { name: "Temjanika Spasić 0.75L", price: "3900 RSD" },
      { name: "Regent Aleksandrović 0.75L", price: "6000 RSD" },
      { name: "Malvazija Kozlović 0.75L", price: "5000 RSD" },
      { name: "Marina Cvetic 0.75L", price: "7000 RSD" },
      { name: "Chardonnay Đorđević 0.75L", price: "3800 RSD" },
      { name: "Sauvignon Blanc Đorđević 0.75L", price: "3500 RSD" },
      { name: "Aleksić Žuti Cvet 0.75L", price: "3600 RSD" },
      { name: "Aleksić Nostalgija 0.75L", price: "3600 RSD" },
      { name: "Prosecco Frassinelli 0.75L", price: "3800 RSD" },
      { name: "Freixenet Carta Nevada 0.75L", price: "3300 RSD" },
      { name: "Moet Chandon Rose 0.75L", price: "21000 RSD" },
      { name: "Moet & Chandon Brut 0.7L", price: "18000 RSD" },
      { name: "Somersby marakuja 0.33L", price: "400 RSD" },
      { name: "Somersby mandarina", price: "400 RSD" },
      { name: "Aleksić Mozaik 1L", price: "3000 RSD" },
      { name: "Somersby malina", price: "490 RSD" },
      { name: "Đorđević Cabernet Merlot 0.75L", price: "3800 RSD" },
      { name: "Somersby breskva 0.33L", price: "490 RSD" },
    ],
  },
  {
    name: "Whisky",
    items: [
      { name: "Johnnie Walker 0.03L", price: "420 RSD" },
      { name: "Chivas Regal 0.03L", price: "600 RSD" },
      { name: "Jack Daniels 0.03L", price: "490 RSD" },
      { name: "Jack Daniels 1L", price: "12900 RSD" },
      { name: "Ballantines 0.03L", price: "400 RSD" },
      { name: "Jameson 1L", price: "11900 RSD" },
      { name: "Jim Beam Whiskey 0.03L", price: "400 RSD" },
      { name: "Johnnie Walker Black 0.03L", price: "650 RSD" },
      { name: "Glenfiddich 12 YO 0.70L", price: "580 RSD" },
      { name: "Tullamore Dew 12 YO 0.03L", price: "750 RSD" },
      { name: "Jack Daniels Barrel 0.03L", price: "690 RSD" },
      { name: "Jameson 0.03L", price: "470 RSD" },
      { name: "Johnnie Walker 1L", price: "10900 RSD" },
      { name: "Johnnie Walker 0.7L", price: "7900 RSD" },
      { name: "Chivas Regal 1L", price: "13900 RSD" },
      { name: "Chivas Regal 0.7L", price: "9900 RSD" },
      { name: "Jameson 0.7L", price: "8500 RSD" },
      { name: "Jack Daniels 0.7L", price: "9500 RSD" },
    ],
  },
  {
    name: "Ceđeni sokovi",
    items: [
      { name: "Limunada 0.2L", price: "450 RSD" },
      { name: "Ceđena narandža 0.25L", price: "490 RSD" },
      { name: "Imuno mix 0.25L", price: "550 RSD" },
      { name: "Ceđeni grejp 0.25L", price: "500 RSD" },
      { name: "Limunada sa ukusima", price: "550 RSD" },
      { name: "Iced Tea", price: "450 RSD" },
    ],
  },
  {
    name: "Nektar",
    items: [
      { name: "Borovnica 0.2L", price: "350 RSD" },
      { name: "Breskva 0.2L", price: "350 RSD" },
      { name: "Đus 0.2L", price: "350 RSD" },
      { name: "Jagoda 0.2L", price: "350 RSD" },
      { name: "Jabuka 0.2L", price: "350 RSD" },
    ],
  },
  {
    name: "Likeri",
    items: [
      { name: "Martini bianco 0.05L", price: "470 RSD" },
      { name: "Gorki list 0.03L", price: "290 RSD" },
      { name: "Baileys 0.05L", price: "450 RSD" },
      { name: "Jägermeister 0.03L", price: "410 RSD" },
      { name: "Campari 0.03L", price: "480 RSD" },
      { name: "Aperol 0.05L", price: "430 RSD" },
      { name: "Vermouth 0.05L", price: "450 RSD" },
      { name: "Malina žuža rakija 0.03L", price: "390 RSD" },
    ],
  },
  {
    name: "Alkohol",
    items: [
      { name: "Finlandia vodka 0.03L", price: "450 RSD" },
      { name: "Vinjak Rubin 0.03L", price: "290 RSD" },
      { name: "Vinjak 5 0.03L", price: "380 RSD" },
      { name: "Courvoisier VS 0.03L", price: "600 RSD" },
      { name: "Vinjak XO 0.7L", price: "790 RSD" },
      { name: "Russian Standard original 0.03L", price: "350 RSD" },
      { name: "Grey Goose Vodka 0.03L", price: "700 RSD" },
      { name: "Old Pascas White Rum", price: "350 RSD" },
      { name: "Sailor Jerry Rum 0.03L", price: "370 RSD" },
      { name: "Tequila Sierra Gold 0.03L", price: "350 RSD" },
      { name: "Tequila Silver Sierra 0.03L", price: "350 RSD" },
      { name: "Hennessy VS 0.03L", price: "750 RSD" },
      { name: "Beefeater Pink Gin 0.03L", price: "380 RSD" },
      { name: "Hendrick's Gin", price: "550 RSD" },
      { name: "Beefeater Gin 0.03L", price: "350 RSD" },
      { name: "Hendrick's 0.7L", price: "12000 RSD" },
      { name: "Smirnoff vodka 0.03L", price: "350 RSD" },
      { name: "Smirnoff Vodka 0.7L", price: "7000 RSD" },
    ],
  },
  {
    name: "Rakije",
    items: [
      { name: "Meduška Boginja meda 0.03L", price: "290 RSD" },
      { name: "Dunja art 0.03L", price: "300 RSD" },
      { name: "Šljiva Voćar Kopaonik 0.03L", price: "330 RSD" },
      { name: "Dunja Voćar Kopaonik 0.03L", price: "350 RSD" },
      { name: "Kajsija Voćar Kopaonik 0.03L", price: "350 RSD" },
      { name: "Samar šljiva 0.03L", price: "450 RSD" },
      { name: "Medovina Sokolova 0.03L", price: "390 RSD" },
      { name: "Žarić Koketa višnja 0.03L", price: "350 RSD" },
      { name: "Zlatni tok šljiva 0.03L", price: "490 RSD" },
      { name: "Loza 13. Juli", price: "280 RSD" },
      { name: "Šljiva tok", price: "430 RSD" },
      { name: "Viljamovka Takovo 0.03L", price: "270 RSD" },
      { name: "Loza Voćar Kopaonik 0.03L", price: "290 RSD" },
      { name: "Viljamovka Voćar 0.03L", price: "330 RSD" },
      { name: "Šljiva Trivunova 0.03L", price: "290 RSD" },
      { name: "Dunja Takovo 0.03L", price: "250 RSD" },
    ],
  },
  {
    name: "Kokteli",
    items: [
      { name: "Blue Curacao Koktel", price: "890 RSD" },
      { name: "Aperol Spritz", price: "790 RSD" },
      { name: "Margarita", price: "650 RSD" },
      { name: "Sex on the Beach", price: "900 RSD" },
      { name: "Cosmopolitan", price: "990 RSD" },
      { name: "Long Island", price: "990 RSD" },
      { name: "Tropical", price: "850 RSD" },
      { name: "Strawberry Passion", price: "750 RSD" },
      { name: "Negroni", price: "950 RSD" },
      { name: "Campari Tonic", price: "700 RSD" },
      { name: "Mojito", price: "850 RSD" },
      { name: "Batman", price: "550 RSD" },
      { name: "Piña Colada", price: "850 RSD" },
      { name: "Mojito u boji", price: "550 RSD" },
      { name: "Lime Cooler", price: "650 RSD" },
      { name: "Sweet Dreams", price: "700 RSD" },
      { name: "Studio Koktel", price: "750 RSD" },
      { name: "Mai Tai", price: "850 RSD" },
      { name: "Gorki List Spritz", price: "950 RSD" },
      { name: "Hugo", price: "890 RSD" },
      { name: "Blue Frog", price: "990 RSD" },
      { name: "God Father", price: "700 RSD" },
      { name: "Monkey", price: "350 RSD" },
      { name: "Tequila Sunrise", price: "890 RSD" },
      { name: "Džin Tonik", price: "350 RSD" },
      { name: "Bitter Vodka", price: "350 RSD" },
      { name: "Đus Vodka", price: "350 RSD" },
    ],
  },
  {
    name: "Vode",
    items: [
      { name: "Romerquelle 0.33L", price: "390 RSD" },
      { name: "Knjaz Miloš limun 0.33L", price: "350 RSD" },
      { name: "Aqua Viva 0.33L", price: "300 RSD" },
      { name: "Knjaz Miloš 0.33L", price: "300 RSD" },
      { name: "Aqua Viva 0.75L", price: "300 RSD" },
      { name: "Knjaz Miloš 0.75L", price: "300 RSD" },
      { name: "Knjaz Miloš narandža 0.33L", price: "330 RSD" },
      { name: "Aqua 1L", price: "450 RSD" },
      { name: "Knjaz 1L", price: "450 RSD" },
    ],
  },
];
